# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Update
      - name: Update package database
        run: sudo apt-get update -qy

      # Install deps
      - name: Install deps
        run: sudo apt-get install -y libfuse2 libsdl2-dev zlib1g-dev libfreetype2-dev libpng-dev 

      # Build sameboy
      - name: Building mupen64plus...
        run: sh scripts/build_mupen64plus.sh

      # Make appimage
      - name: Making appimage...
        run: sh scripts/make_appimage.sh

      # Upload appimage
      - name: Uploading appimage...
        uses: actions/upload-artifact@v3
        with:
          name: Mupen64Plus-v2.5-x86_64
          path: |
            mupen64plus-bundle-src-2.5/Mupen64Plus-v2.5-x86_64.AppImage
            mupen64plus-bundle-src-2.5/Mupen64Plus-v2.5-x86_64.AppImage.zsync
